services:
  # frontend:
  #   build: 
  #     context: .
  #     args:
  #       - BACKEND_URL=example.com
  #     dockerfile: Dockerfile
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "80:80"
  
  test:
    image: ghcr.io/ubclaunchpad/neuron-frontend:3a853af26bef550447a6e26cd5f930f811db7577
    ports:
      - "80:80"