version: '3.7'

services:
  frontend:
    image: ghcr.io/ubclaunchpad/neuron-frontend:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"  # Port for react app
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
    deploy:
      update_config:
        order: start-first

  backend:
    image: ghcr.io/ubclaunchpad/neuron-backend:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3001" # Backend api port
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    secrets:
      - gmail_password
      - token_secret
      - rds_password
    environment:
      - RDS_HOSTNAME=${RDS_HOSTNAME}
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_PASSWORD_FILE=/run/secrets/rds_password
      - RDS_PORT=${RDS_PORT}
      - RDS_DB=${RDS_DB}
      - TOKEN_SECRET_FILE=/run/secrets/token_secret
      - GMAIL_ID=${GMAIL_ID}
      - GMAIL_PASSWORD_FILE=/run/secrets/gmail_password
      - HOST=${CONTAINER_URL}/api
      - FRONTEND_HOST=${CONTAINER_URL}
      - NEURON_ENV=production
    deploy:
      update_config:
        order: start-first

  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=neuronbc@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--api.insecure=true"
    ports:
      - mode: host  # Port to forward HTTP to HTTPS
        protocol: tcp
        published: 80
        target: 80
      - mode: host  # Port for HTTPS
        protocol: tcp
        published: 443
        target: 443
      - "8080:8080"  # Port for Traefik dashboard
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  letsencrypt:

secrets:
  gmail_password:
    external: true
  token_secret:
    external: true
  rds_password:
    external: true
