version: '3.7'

services:
  frontend:
    image: neuron-frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`x.x.x.x`) && PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"  # Port for react app

  backend:
    image: neuron-backend-image
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`x.x.x.x`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000" # Backend api port

  traefik:
    image: "traefik:v2.5"
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80" # HTTP port for routing
      - "8080:8080" # Port for Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" 

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'neuron'
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db: