"use client";

import React, { useRef, useState, useEffect } from "react";
import FullCalendar from "@fullcalendar/react";
import timeGridPlugin from "@fullcalendar/timegrid";
import dayGridPlugin from "@fullcalendar/daygrid";
import type { EventClickArg, DayHeaderContentArg } from "@fullcalendar/core";
import "./page.scss";
import { ButtonGroup } from "@/components/primitives/button-group";
import { Button } from "@/components/primitives/button";
import CaretLeftIcon from "@public/assets/icons/caret-left.svg";
import CaretRightIcon from "@public/assets/icons/caret-right.svg";
import { useCalendarApi } from "./useCalendarApi";
import { useDayView } from "./useDayView";
import { isSameDay, CalendarView } from "./dateUtils";
import { dummyShifts } from "./mockShifts";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/primitives/select";

export function ScheduleCalendarView({
  onSelectShift,
}: {
  onSelectShift: (shiftId: string) => void;
}) {
  const calendarRef = useRef<FullCalendar | null>(null);
  const calendarContainerRef = useRef<HTMLDivElement>(null);
  const { calendarApi, next, prev, changeView, getDate, goToDate } = useCalendarApi(calendarRef);
  const { isDayView, selectedDate, setSelectedDate, renderDayViewHeader } = useDayView({
    calendarApi,
    next,
    prev,
    changeView,
    getDate,
    goToDate,
    calendarContainerRef,
  });

  // Render calendar in appropriate view
  useEffect(() => {
    if (!calendarApi) return;

    queueMicrotask(() => {
      if (isDayView) {
        calendarApi.changeView(CalendarView.Day, selectedDate);
      } else {
        calendarApi.changeView(CalendarView.Week);
      }
    });
  }, [calendarApi, selectedDate, isDayView]);

  // Keep FullCalendar width in sync with layout changes (e.g. opening/closing the aside).
  // ResizeObserver picks up the PageLayout aside animation and we debounce via rAF
  // so FullCalendar can recompute column widths without jitter.
  // This part was generated by ChatGPT to help with some animation nuances.
  useEffect(() => {
    const container = calendarContainerRef.current;
    if (!container) return;

    let frameId: number | null = null;
    let lastWidth = container.getBoundingClientRect().width;

    const observer = new ResizeObserver((entries) => {
      // only react to the first and only observed element
      const entry = entries[0];
      if (!entry) return;

      const { width } = entry.contentRect;
      // skip if nothing actually changed
      if (width === lastWidth) return;
      lastWidth = width;

      const api = calendarRef.current?.getApi();
      if (!api) return;

      // Wait until the next animation frame so updateSize runs once per frame
      // instead of every tiny resize while the aside animates
      if (frameId) cancelAnimationFrame(frameId);
      frameId = requestAnimationFrame(() => api.updateSize());
    });

    observer.observe(container);

    return () => {
      if (frameId) cancelAnimationFrame(frameId);
      observer.disconnect();
    };
  }, []);

  const handleNavAction = (navAction: "today" | "prev" | "next") => {
    const calendarApi = calendarRef.current?.getApi();
    if (!calendarApi) return;

    calendarApi[navAction]();
    setSelectedDate(calendarApi.getDate());
  };

  const renderNavBar = () => {
    return <div className="navbar">
        <div className="navbar-left">
          <ButtonGroup className="navbar-buttons">
            <Button variant="ghost" onClick={() => handleNavAction("today")}>Today</Button>
            <Button variant="ghost" onClick={() => handleNavAction("prev")}><CaretLeftIcon/></Button>
            <Button variant="ghost" onClick={() => handleNavAction("next")}><CaretRightIcon/></Button>
          </ButtonGroup>
          <div className="pl-4">{selectedDate.toLocaleDateString("en-US", {month: "long", year: "numeric"})}</div>
          {/* <Select>
            <SelectTrigger>
              <SelectValue placeholder={selectedDate.toLocaleDateString("en-US", {month: "long", year: "numeric"})} />
            </SelectTrigger>
            <SelectContent className="max-h-80 overflow-y-auto">
              {monthList.map((date: Date) => (
                <SelectItem key={date.toISOString()} value={date.toISOString()} className="cursor-pointer">
                  {date.toLocaleDateString("en-US", {month: "long", year: "numeric"})}
                </SelectItem>
              ))}
            </SelectContent>
          </Select> */}
        </div>
        {/* <div className="ml-auto">
          <Select value={currentView} onValueChange={(value) => handleViewChange(value as CalendarView)}>
            <SelectTrigger className="w-[150px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value={CalendarView.Week}>Week view</SelectItem>
              <SelectItem value={CalendarView.Day}>Day view</SelectItem>
            </SelectContent>
          </Select>
        </div> */}
        {/* <div>
          {!isDayView && <Select onValueChange={(v) => queueMicrotask(() => calendarRef.current?.getApi().changeView(v))}>
            <SelectTrigger className="w-[150px]">
              <SelectValue placeholder="Choose view" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="dayGridMonth">Month</SelectItem>
              <SelectItem value="timeGridWeek">Week</SelectItem>
              <SelectItem value="listView">list</SelectItem>
            </SelectContent>
          </Select>}
        </div> */}
      </div>
  };

  const renderWeekHeader = (arg: DayHeaderContentArg) => {
    const date: Date = arg.date;
    const isToday = isSameDay(date, new Date());

    const dayName: string = date.toLocaleDateString("en-US", { weekday: "long" });
    const dayNum: number = date.getDate();

    return (
      <div className={`week-header ${isToday ? "week-header-current-day" : ""}`}>
        <div style={{ fontSize: "24px" }}>{dayNum}</div>
        <div style={{ fontSize: "14px" }}>{dayName}</div>
      </div>
    )
  };

  const handleEventClick = (info: EventClickArg) => {
    onSelectShift(info.event.id);
    setSelectedDate(info.event.start!);
  };

  return (
    <>
      {renderNavBar()}
      {isDayView && renderDayViewHeader()}
      <div ref={calendarContainerRef}>
        <FullCalendar
          ref={calendarRef}
          plugins={[dayGridPlugin, timeGridPlugin]}
          initialView={CalendarView.Week}
          headerToolbar={false}
          dayHeaderContent={(arg) => {
            if (isDayView) return null;
            if (arg.view.type === CalendarView.Month) return <div>{arg.text}</div>;

            return renderWeekHeader(arg);
          }}
          height="auto"
          slotMinTime="09:00:00"
          allDaySlot={false}
          eventClick={handleEventClick}
          firstDay={1}
          events={dummyShifts.map((shift) => ({
            id: shift.id,
            title: shift.class?.name ?? "Unnamed shift",
            start: shift.startAt,
            end: shift.endAt,
          }))}
        />
      </div>
    </>
  );
}
