"use client";

import {
  PageLayout,
  PageLayoutAside,
  PageLayoutHeader,
  PageLayoutHeaderContent,
  PageLayoutHeaderTitle,
  usePageAside
} from "@/components/page-layout";

import {
    Select,
    SelectContent,
    SelectGroup,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/primitives/select";


import React, { useRef, useState, useEffect } from "react";
import FullCalendar from "@fullcalendar/react";
import timeGridPlugin from "@fullcalendar/timegrid";
import dayGridPlugin from "@fullcalendar/daygrid";
import type { EventClickArg, DayHeaderContentArg } from "@fullcalendar/core";
import "./page.scss";
import { ButtonGroup } from "@/components/primitives/button-group";
import { Button } from "@/components/primitives/button";
import CaretLeftIcon from "@public/assets/icons/caret-left.svg";
import CaretRightIcon from "@public/assets/icons/caret-right.svg";
import { useCalendarApi } from "./useCalendarApi";
import { useDayView } from "./useDayView";
import { isSameDay, CalendarView, generateMonthRange } from "./dateUtils";
import type { Shift } from "@/models/shift";
import { CalendarAside } from "./useCalendarAside";

/// The following dummy data is generated by chatGPT for testing purposes
export const dummyShifts: Shift[] = [
  {
    id: "shift-1",
    date: "2025-11-21",
    startAt: new Date("2025-11-28T10:00:00"),
    endAt: new Date("2025-11-28T11:30:00"),
    canceled: false,

    class: {
      id: "class-1",
      termId: "term-1",
      name: "Beginner Coding",
      description: "Intro to programming for beginners.",
      image: "/images/classes/beginner-coding.png",
      published: true,
      meetingURL: "https://meet.example.com/class-1",
      category: "Education",
      subcategory: "Programming",
      lowerLevel: 1,
      upperLevel: 3,
      schedules: [], // empty for now
      createdAt: new Date("2024-01-01T00:00:00"),
      updatedAt: new Date("2024-06-01T00:00:00"),
    },
  
    schedule: {
      id: "schedule-1",
      durationMinutes: 120,
      effectiveStart: "2025-03-01",
      effectiveEnd: "2025-12-31",
      rule: {
        type: "weekly",
        weekday: "MO",
        interval: 1,
        localStartTime: "00:00:00",
        tzid: "12345",
      },
      instructors: [],
      volunteers: [],
    },


    volunteers: [
      {
        id: "vol-1",
        name: "Alice",
        lastName: "Johnson",
        preferredName: "Ali",
        bio: "Enthusiastic volunteer and mentor.",
        pronouns: "she/her",
        phoneNumber: "555-123-4567",
        city: "Seattle",
        province: "WA",
        availability: "Weekdays",
        preferredTimeCommitmentHours: 5,
        email: "alice@example.com",
        status: "active",
        image: "/images/volunteers/alice.png",
        createdAt: new Date("2024-02-01T00:00:00"),
        updatedAt: new Date("2024-05-01T00:00:00"),
        emailVerified: true,
      }
    ],
  },

  // SECOND SHIFT
  {
    id: "shift-2",
    date: "2025-11-21",
    startAt: new Date("2025-11-28T13:00:00"),
    endAt: new Date("2025-11-28T15:00:00"),
    canceled: false,

    class: {
      id: "class-2",
      termId: "term-1",
      name: "Advanced Robotics",
      description: "Hands-on robotics workshop.",
      published: true,
      image: "/images/classes/advanced-robotics.png",
      meetingURL: "https://meet.example.com/class-2",
      category: "STEM",
      subcategory: "Robotics",
      lowerLevel: 4,
      upperLevel: 6,
      schedules: [],
      createdAt: new Date("2024-03-10T00:00:00"),
      updatedAt: new Date("2024-06-15T00:00:00"),
    },

    schedule: {
      id: "schedule-2",
      durationMinutes: 120,
      effectiveStart: "2025-03-01",
      effectiveEnd: "2025-12-31",
      rule: {
        type: "weekly",
        weekday: "MO",
        interval: 1,
        localStartTime: "00:00:00",
        tzid: "12345",
      },
      instructors: [],
      volunteers: [],
    },

    volunteers: [
      {
        id: "vol-2",
        name: "Brian",
        lastName: "Lee",
        preferredName: "Bri",
        pronouns: "he/him",
        bio: "Volunteer passionate about robotics and education.",
        phoneNumber: "555-888-9999",
        city: "Portland",
        province: "OR",
        availability: "Fridays",
        preferredTimeCommitmentHours: 4,
        email: "brian@example.com",
        status: "active",
        image: "/images/volunteers/brian.png",
        createdAt: new Date("2024-03-20T00:00:00"),
        updatedAt: new Date("2024-05-10T00:00:00"),
        emailVerified: true,
      }
    ],
  },
];

export function ScheduleView() {
  const calendarRef = useRef<FullCalendar | null>(null);
  const { calendarApi, next, prev, changeView, getDate, goToDate } = useCalendarApi(calendarRef);
  const { isDayView, selectedDate, setSelectedDate, renderDayViewHeader } = useDayView({ calendarApi, next, prev, changeView, getDate, goToDate });
  const [currentView, setCurrentView] = useState<CalendarView>(CalendarView.Week);
  const [selectedShift, setSelectedShift] = useState<Shift | undefined>(undefined);
  const { setOpen } = usePageAside();

  // Render calendar in appropriate view
  useEffect(() => {
    if (!calendarApi) return;

    queueMicrotask(() => {
    if (isDayView) {
      calendarApi.changeView(CalendarView.Day, selectedDate);
      setCurrentView(CalendarView.Day);
    } else {
      calendarApi.changeView(CalendarView.Week, selectedDate);
      setCurrentView(CalendarView.Week);
    }
    });
  }, [isDayView, selectedDate]);

  const handleNavAction = (navAction: "today" | "prev" | "next") => {
    const calendarApi = calendarRef.current?.getApi();
    if (!calendarApi) return;

    calendarApi[navAction]();
    setSelectedDate(calendarApi.getDate());
  };

  const renderNavBar = () => {
    const monthList = generateMonthRange(new Date());

    return <div className="navbar">
        <div className="navbar-left">
          <ButtonGroup className="navbar-buttons">
            <Button variant="ghost" onClick={() => handleNavAction("today")}>Today</Button>
            <Button variant="ghost" onClick={() => handleNavAction("prev")}><CaretLeftIcon/></Button>
            <Button variant="ghost" onClick={() => handleNavAction("next")}><CaretRightIcon/></Button>
          </ButtonGroup>
          <div className="pl-4">{selectedDate.toLocaleDateString("en-US", {month: "long", year: "numeric"})}</div>
          {/* <Select>
            <SelectTrigger>
              <SelectValue placeholder={selectedDate.toLocaleDateString("en-US", {month: "long", year: "numeric"})} />
            </SelectTrigger>
            <SelectContent className="max-h-80 overflow-y-auto">
              {monthList.map((date: Date) => (
                <SelectItem key={date.toISOString()} value={date.toISOString()} className="cursor-pointer">
                  {date.toLocaleDateString("en-US", {month: "long", year: "numeric"})}
                </SelectItem>
              ))}
            </SelectContent>
          </Select> */}
        </div>
        {/* <div>
          {!isDayView && <Select onValueChange={(v) => queueMicrotask(() => calendarRef.current?.getApi().changeView(v))}>
            <SelectTrigger className="w-[150px]">
              <SelectValue placeholder="Choose view" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="dayGridMonth">Month</SelectItem>
              <SelectItem value="timeGridWeek">Week</SelectItem>
            </SelectContent>
          </Select>}
        </div> */}
      </div>
  };

  const renderWeekHeader = (arg: DayHeaderContentArg) => {
    const date: Date = arg.date;
    const isToday = isSameDay(date, new Date());

    const dayName: string = date.toLocaleDateString("en-US", { weekday: "long" });
    const dayNum: number = date.getDate();

    return (
      <div className={`week-header ${isToday ? "week-header-current-day" : ""}`}>
        <div style={{ fontSize: "24px" }}>{dayNum}</div>
        <div style={{ fontSize: "14px" }}>{dayName}</div>
      </div>
    )
  };

  const handleEventClick = (info: EventClickArg) => {
    const shift = dummyShifts.find(s => s.id === info.event.id);
    if (!shift) return;
    setSelectedShift(shift);
    setOpen(true);
  };

  return (
    <>
        <PageLayoutHeader>
          <PageLayoutHeaderContent>
              <PageLayoutHeaderTitle>Schedule</PageLayoutHeaderTitle>
          </PageLayoutHeaderContent>
              {renderNavBar()}
        </PageLayoutHeader>
      
      <PageLayoutAside>
        <CalendarAside shift={selectedShift} />
      </PageLayoutAside>

      {isDayView && renderDayViewHeader()}

      <FullCalendar
        ref={calendarRef}
        plugins={[dayGridPlugin, timeGridPlugin]}
        initialView={CalendarView.Week}
        headerToolbar={false}
        dayHeaderContent={(arg) => {
          if (isDayView) return null;
          if (arg.view.type === CalendarView.Month) return <div>{arg.text}</div>;

          return renderWeekHeader(arg);
        }}
        height="auto"
        slotMinTime="09:00:00"
        allDaySlot={false}
        eventClick={handleEventClick}
        firstDay={1}
        events={dummyShifts.map((shift) => ({
          id: shift.id,
          title: shift.class?.name ?? "Unnamed shift",
          start: shift.startAt,
          end: shift.endAt,
        }))}
      />
    </>
  );
}
