import { RowDataPacket } from "mysql2";

/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface Admin extends RowDataPacket {
  'admin_id': string;
  'f_name': string;
  'fk_user_id'?: string | null;
  'l_name': string;
}
export interface Availability extends RowDataPacket {
  'availability_id'?: number;
  'day': number;
  'end_time': string;
  'fk_volunteer_id': string;
  'start_time': string;
}
export interface Class extends RowDataPacket {
  'category'?: string | null;
  'class_id'?: number;
  'class_name': string;
  'end_date': string;
  'fk_image_id'?: string | null;
  'fk_instructor_id': string;
  'instructions'?: string | null;
  'start_date': string;
  'subcategory'?: string | null;
  'zoom_link': string;
}
export interface ClassImage extends RowDataPacket {
  'fk_class_id'?: number | null;
  'image'?: Buffer | null;
  'image_id'?: number;
}
export interface ClassPreference extends RowDataPacket {
  'class_rank'?: number | null;
  'fk_class_id'?: number | null;
  'fk_volunter_id'?: string | null;
}
export interface Image extends RowDataPacket {
  'image': Buffer;
  'image_id': string;
}
export interface Instructor extends RowDataPacket {
  'email': string;
  'f_name': string;
  'fk_user_id'?: string | null;
  'instructor_id': string;
  'l_name': string;
}
export interface PendingShiftCoverage extends RowDataPacket {
  'pending_volunteer': string;
  'request_id': number;
}
export interface Schedule extends RowDataPacket {
  'day': number;
  'end_time': string;
  'fk_class_id': number;
  'schedule_id'?: number;
  'start_time': string;
}
export interface ShiftCoverageRequest extends RowDataPacket {
  'covered_by'?: string | null;
  'fk_schedule_id': number;
  'fk_volunteer_id': string;
  'request_id'?: number;
  'shift_date': string;
}
export interface Shift extends RowDataPacket {
  'checked_in'?: any | null;
  'duration': number;
  'fk_schedule_id': number;
  'fk_volunteer_id': string;
  'shift_date': string;
}
export interface User extends RowDataPacket {
  'created_at'?: Date | null;
  'email': string;
  'fk_image_id'?: string | null;
  'password': string;
  'role': string;
  'user_id': string;
}
export interface VolunteerClass extends RowDataPacket {
  'fk_class_id': number;
  'fk_volunteer_id': string;
}
export interface VolunteerProfilePic extends RowDataPacket {
  'fk_volunteer_id': string;
  'profile_pic': Buffer;
}
export interface Volunteer extends RowDataPacket {
  'active'?: any | null;
  'bio'?: string | null;
  'city'?: string | null;
  'email': string;
  'f_name': string;
  'fk_user_id'?: string | null;
  'l_name': string;
  'p_name'?: string | null;
  'phone_number'?: string | null;
  'pronouns'?: string | null;
  'province'?: string | null;
  'total_hours'?: number;
  'volunteer_id': string;
}
