/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface Admin {
  'admin_id': string;
  'f_name': string;
  'fk_user_id'?: string | null;
  'l_name': string;
}
export interface Availability {
  'availability_id'?: number;
  'day': number;
  'end_time': string;
  'fk_volunteer_id': string;
  'start_time': string;
}
export interface Class {
  'category'?: string | null;
  'class_id'?: number;
  'class_name': string;
  'end_date': string;
  'fk_instructor_id': string;
  'instructions'?: string | null;
  'start_date': string;
  'subcategory'?: string | null;
  'zoom_link': string;
}
export interface ClassImage {
  'fk_class_id'?: number | null;
  'image'?: Buffer | null;
  'image_id'?: number;
}
export interface ClassPreference {
  'class_rank'?: number | null;
  'fk_class_id'?: number | null;
  'fk_volunteer_id'?: string | null;
}
export interface Instructor {
  'email': string;
  'f_name': string;
  'fk_user_id'?: string | null;
  'instructor_id': string;
  'l_name': string;
}
export interface PendingShiftCoverage {
  'pending_volunteer': string;
  'request_id': number;
}
export interface Schedule {
  'day': number;
  'end_time': string;
  'fk_class_id': number;
  'schedule_id'?: number;
  'start_time': string;
}
export interface ShiftCoverageRequest {
  'covered_by'?: string | null;
  'fk_schedule_id': number;
  'fk_volunteer_id': string;
  'request_id'?: number;
  'shift_date': string;
}
export interface Shift {
  'checked_in'?: any | null;
  'duration': number;
  'fk_schedule_id': number;
  'fk_volunteer_id': string;
  'shift_date': string;
}
export interface User {
  'created_at'?: Date | null;
  'email': string;
  'password': string;
  'role': string;
  'user_id': string;
}
export interface VolunteerClass {
  'fk_class_id': number;
  'fk_volunteer_id': string;
}
export interface VolunteerProfilePic {
  'fk_volunteer_id': string;
  'profile_pic': Buffer;
}
export interface Volunteer {
  'active'?: any | null;
  'bio'?: string | null;
  'city'?: string | null;
  'email': string;
  'f_name': string;
  'fk_user_id'?: string | null;
  'l_name': string;
  'p_name'?: string | null;
  'phone_number'?: string | null;
  'pronouns'?: string | null;
  'province'?: string | null;
  'total_hours': number;
  'volunteer_id': string;
}
